------------------------------------------------------------------------------------------------------------------------------------
--Ejercicios SQL Nivel Intermedio (21–60) 
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[21] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Listar proyectos con el total del presupuesto utilizado por las tareas asignadas (suponiendo que cada tarea consume un porcentaje del presupuesto).

--(Tareas Pendientes 20% Tareas En Progreso 70% Tareas Pendientes 10%)
--SELECT *,
--	CASE 
--	WHEN a.Estado = 'Pendiente' THEN CAST(Presupuesto * 20/100 AS INT) --Formula (Presupuesto*20)/100
--	WHEN a.Estado = 'En Progreso' THEN CAST(Presupuesto * 70/100 AS INT) --Formula (Presupuesto*70)/100
--	WHEN a.Estado = 'Terminada' THEN CAST(Presupuesto * 10/100 AS INT) --Formula (Presupuesto*10/100)
--	END AS PorcentajeActualDePresupuesto
--FROM TAREAS a
--INNER JOIN PROYECTO b ON b.Id_Proyecto = a.FK_ProyectoId
--ORDER BY a.Ciudad_Proyecto DESC, a.Estado DESC
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[22] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Para cada proyecto, la cantidad total de tareas asignadas.
--Para cada tarea, el empleado asignado y el estado de la tarea.
--Para cada empleado, la cantidad de tareas asignadas por proyecto y el porcentaje que representan respecto al total de tareas de ese proyecto.
--Además, que el estado de las tareas se represente con los siguientes íconos:
--Pendiente ¥
--En Progreso »
--Terminada !

--SELECT 
--a.Nombre AS NombreProyecto,	b.Descripcion AS NombreTarea,
--d.Nombre +' '+ d.Apellido AS EmpleadoAsignado, COUNT(c.FK_TareaId) AS TotalDeTareasAsignadas, 
--b.Estado, b.ciudad_proyecto,
--CASE
--	WHEN b.Estado = 'Pendiente' THEN '¥'
--	WHEN b.Estado = 'En Progreso' THEN '»'
--	WHEN b.Estado = 'Terminada' THEN '!'
--	END AS Iconos,
--FORMAT(
--    COUNT(c.FK_TareaId) * 100.0 / 
--    (
--      SELECT COUNT(*) 
--      FROM TAREAS t 
--      WHERE t.Ciudad_Proyecto = b.Ciudad_Proyecto
--    ),
--  'N1') + '%' AS PorcentajeCiudad
--FROM PROYECTO a
--INNER JOIN TAREAS b ON b.FK_ProyectoId = a.Id_Proyecto
--INNER JOIN EMPLEADO_TAREA c ON c.FK_TareaId = b.Id_Tarea
--INNER JOIN EMPLEADO d ON d.Id_Empleado = c.FK_EmpleadoId
--GROUP BY a.Nombre, c.FK_TareaId, b.Descripcion, d.Nombre, d.Apellido, b.Estado, b.Ciudad_Proyecto
--ORDER BY c.FK_TareaId ASC
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[23] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Listar empleados que no tienen tareas asignadas, mostrando su ubicación y clasificándolos según tiempo de contratación (más o menos de un año).

--SELECT 
--	a.Nombre +' '+ a.Apellido AS Empleado, c.Ubicacion,
--CASE 
--	WHEN a.Fecha_Contratacion < '2025-01-01' THEN 'Contrato Antiguo Sin Tareas Asignadas' ELSE 'Contrato Nuevo Sin Tareas Asignadas'
--	END AS Clasificacion 
--FROM 
--	EMPLEADO a
--	LEFT JOIN EMPLEADO_TAREA b ON b.FK_EmpleadoId = a.Id_Empleado
--	INNER JOIN UBICACION c ON c.Id_Ubicacion = a.FK_UbicacionId
--WHERE 
--	B.FK_TareaId IS NULL
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[24] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Obtener todos los proyectos con la mayor cantidad de tareas asignadas (considerar empates), e incluir el porcentaje de tareas completadas para cada proyecto.

--;WITH ProyectosTareas AS(
--SELECT 
--	p.Nombre AS Proyecto,
--	COUNT(et.FK_TareaId) AS TareasAsignadas,
--	SUM(CASE WHEN t.estado = 'Terminada' THEN 1 ELSE 0 END) AS TareasTerminadas
--FROM 
--	PROYECTO p
--INNER JOIN
--	TAREAS t ON t.FK_ProyectoId = p.Id_Proyecto
--INNER JOIN
--	EMPLEADO_TAREA et ON et.FK_TareaId = t.Id_Tarea
--GROUP BY p.Nombre
--)
--SELECT 
--	Proyecto, TareasAsignadas, TareasTerminadas,
--	ROUND(CAST(TareasTerminadas AS FLOAT) * 100 / NULLIF(TareasAsignadas, 0), 2) AS PorcentajeCompletadas
--FROM ProyectosTareas
--WHERE TareasAsignadas = (SELECT MAX(TareasAsignadas) FROM ProyectosTareas) 
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[25] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Para cada empleado, mostrar su salario, la suma total de salarios de todos los empleados en su misma ubicación.

--WITH SalriosEmpleados AS(
--	SELECT 
--		em.Nombre,
--		em.Apellido,
--		ub.Ubicacion,
--		em.salario,
--		SUM(em.salario) OVER(PARTITION BY ub.Ubicacion) As TotalSalario,
--		ROW_NUMBER() OVER(PARTITION BY ub.Ubicacion ORDER BY em.Salario ASC) AS RowNumber
--	FROM EMPLEADO em 
--	INNER JOIN UBICACION ub ON ub.Id_Ubicacion = em.FK_UbicacionId
--),
--Prioridad AS(
--	SELECT *,
--		CASE
--			WHEN Ubicacion = 'Bogota' AND RowNumber = 1 THEN 1
--			WHEN Ubicacion = 'Medellin' AND RowNumber = 1 THEN 2
--			WHEN Ubicacion = 'Cali' AND RowNumber = 1 THEN 3
--			WHEN Ubicacion = 'Barranquilla' AND RowNumber = 1 THEN 4
--			WHEN Ubicacion = 'Bogota Medellin' AND RowNumber = 1 THEN 5
--			WHEN Ubicacion = 'Bogota Cali' AND RowNumber = 1 THEN 6
--			WHEN Ubicacion = 'Bogota Barranquilla' AND RowNumber = 1 THEN 7
--			WHEN Ubicacion = 'Medellin Cali' AND RowNumber = 1 THEN 8
--			ELSE 9
--		END AS OrdenPrioridad	
--	FROM SalriosEmpleados
--)
--SELECT
--	ROW_NUMBER() OVER(ORDER BY OrdenPrioridad, Ubicacion, RowNumber) AS Posicion,
--	Nombre +' '+ Apellido AS Empleado,
--	Ubicacion,
--	Salario,
--CASE
--	WHEN Ubicacion = 'Bogota' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_Bogota,
--CASE
--	WHEN Ubicacion = 'Medellin' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_Medellin,
--CASE
--	WHEN Ubicacion = 'Cali' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_Cali,
--CASE
--	WHEN Ubicacion = 'Barranquilla' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_Barranquilla,
--CASE
--	WHEN Ubicacion = 'Bogota Medellin' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_BogotaMedellin,
--CASE 
--	WHEN Ubicacion = 'Bogota Cali' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_BogotaCali,
--CASE
--	WHEN Ubicacion = 'Bogota Barranquilla' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_BogotaBarranquilla,
--CASE
--	WHEN Ubicacion = 'Medellin Cali' AND RowNumber = 1 THEN TotalSalario
--END AS Nomina_MedellinCali
--FROM Prioridad
--ORDER BY Posicion;
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[26] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Listar todas las tareas con estado 'Terminada' y mostrar la cantidad de días que tomó completarlas, calculados entre la fecha de inicio y la fecha de fin

--SELECT *,
--	CASE
--		WHEN Estado = 'Terminada' THEN DATEDIFF(DAY, Fecha_Inicio, Fecha_Fin) 
--		END AS DiasDelProyecto
--FROM TAREAS t 
--WHERE Estado = 'Terminada'
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[27] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Mostrar empleados contratados en los últimos 6 meses, junto con su antigüedad en días y un indicador que clasifique si son “Recién contratado” (< 3 meses) o “Reciente” (3-6 meses).

--SELECT *,
--	CASE
--		WHEN DATEDIFF(MONTH, Fecha_Contratacion, GETDATE()) <3 THEN 'Recién contratado'
--		WHEN DATEDIFF(MONTH, Fecha_Contratacion, GETDATE()) >3 THEN 'Reciente'
--	END AS Antiguedad
--FROM EMPLEADO e
--WHERE Fecha_Contratacion >= DATEADD(MONTH, -6, GETDATE())
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[28] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Listar proyectos activos cuya fecha no sea superior al año 2025, junto con la cantidad de tareas pendientes y completadas.

--;WITH Punto29 AS(
--	SELECT 
--		p.Fecha_Inicio, p.Fecha_Fin, p.Nombre, p.Presupuesto,
--		SUM(CASE WHEN t.Estado = 'En Progreso' THEN 1 ELSE 0 END) AS TareasEnProgreso,
--		SUM(CASE WHEN t.Estado = 'Pendiente' THEN 1 ELSE 0 END) AS TareasPendientes
--	FROM PROYECTO p
--	INNER JOIN TAREAS t ON t.FK_ProyectoId = p.Id_Proyecto
--	WHERE
--		t.Estado = 'En Progreso' OR t.Estado = 'Pendiente'
--	AND t.Fecha_Fin BETWEEN '2025-01-01 00:00:00.000' AND '2025-12-31 00:00:00.997'
--	--AND t.Fecha_Fin <= '2025-12-31 00:00:00.000' (Opcional)
--	GROUP BY
--		p.Fecha_Inicio, p.Fecha_Fin, p.Nombre, p.Presupuesto
--)

--SELECT * FROM Punto29
--ORDER BY TareasPendientes
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[29] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
--Mostrar la cantidad de empleados por ubicación, junto con el salario promedio y el salario máximo en cada ubicación
--;WITH EmpleadosUbicacion AS(
--	SELECT  
--		t.Ciudad_Proyecto,
--		MAX(e.Salario) AS SalarioMaximoNum
--	FROM TAREAS t
--	INNER JOIN EMPLEADO_TAREA et ON et.FK_TareaId = t.Id_Tarea
--	INNER JOIN EMPLEADO e ON e.Id_Empleado = et.FK_EmpleadoId
--	GROUP BY t.Ciudad_Proyecto
--),
--PromedioSalarios AS(
--	SELECT 
--		AVG(SalarioMaximoNum) AS PromedioMaximo
--	FROM EmpleadosUbicacion
--)
--SELECT 
--	e.Nombre, e.Apellido,
--	t.Descripcion, t.Estado, t.Ciudad_Proyecto,
--	CONCAT(eu.Ciudad_Proyecto,' ', eu.SalarioMaximoNum) AS SalarioMaximo,
--	ps.PromedioMaximo
--FROM TAREAS t
--	INNER JOIN EMPLEADO_TAREA et ON et.FK_TareaId = t.Id_Tarea
--	INNER JOIN EMPLEADO e ON e.Id_Empleado = et.FK_EmpleadoId
--	INNER JOIN EmpleadosUbicacion eu ON eu.Ciudad_Proyecto = t.Ciudad_Proyecto
--	CROSS JOIN PromedioSalarios ps
--ORDER BY t.Ciudad_Proyecto ASC;
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[30] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
------------------------------------------------------------------------------------------------------------------------------------
-- Contar tareas agrupadas por estado, y calcular el porcentaje que representan cada estado respecto al total de tareas.
--;WITH Estados AS(
--	SELECT 
--		t.Estado,
--		COUNT(*) AS TotalTatreasEstado
--	FROM TAREAS t
--	GROUP BY Estado
--),
--Porcentajes AS(
--	SELECT 
--	e.Estado,
--	TotalTatreasEstado * 100.0 / (SELECT SUM(TotalTatreasEstado) FROM Estados) AS Porcentaje
--FROM Estados e
--)
--SELECT
--	p.Estado, p.Porcentaje
--FROM Porcentajes p
------------------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------
--[31] ESCRIBE UNA CONSULTA SQL QUE MUESTRE
-------------------------------------------------------------------------------------------------------------------------
--Obtener el salario promedio, mínimo y máximo por ubicación, y mostrar para cada ubicación la diferencia entre el salario máximo y el mínimo.

--;WITH SalarioMinimo AS(
--	SELECT
--		'[Salrios] ' + ISNULL(u.Ubicacion,'') AS SalarioMinimoUbicacion,
--		MIN(e.Salario) AS Minimo,
--		MAX(e.Salario) AS Maximo,
--		AVG(e.Salario) AS Promedio
--		FROM EMPLEADO e
--	INNER JOIN UBICACION u ON u.Id_Ubicacion = e.FK_UbicacionId
--	GROUP BY u.Ubicacion
--)

--SELECT * FROM SalarioMinimo



-------------------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------
--32 Listar proyectos cuyo presupuesto es mayor al promedio general, mostrando cuánto porcentaje por encima del promedio están.
--33 Listar empleados cuyo nombre comienza con 'A' o 'J', indicando si además su salario está por encima o por debajo del salario promedio general.
--34 Mostrar el nombre del empleado y del proyecto para todas las tareas con estado 'En Progreso', junto con la duración actual de la tarea (días desde inicio hasta hoy).
--35 Listar proyectos con la cantidad de empleados distintos que trabajan en ellos, y el porcentaje que representan respecto al total de empleados.
--36 Obtener el empleado con el salario más alto por cada ubicación, mostrando también el promedio salarial de esa ubicación y la diferencia entre el máximo y promedio.
--37 Listar tareas que no tienen fecha de fin (NULL) e indicar si la tarea está retrasada según la fecha actual y la fecha de inicio.
--38 Mostrar empleados que trabajan en proyectos que finalizarán en menos de un mes, con la cantidad de tareas activas asignadas a cada empleado.
--39 Obtener el número de proyectos iniciados en cada año, junto con la suma total y promedio de presupuestos por año.
--40 Listar empleados que tienen tareas en más de un proyecto, mostrando el número de proyectos distintos y el total de tareas asignadas.
--41 Obtener el salario total pagado a empleados por cada proyecto, considerando solo tareas completadas.
--42 Mostrar proyectos y el promedio, mínimo y máximo de duración (en días) de sus tareas, excluyendo tareas sin fecha de fin.
--43 Listar empleados que tienen tareas con diferentes estados (por ejemplo, tareas en ‘Pendiente’ y ‘Completada’), y mostrar un resumen del estado más frecuente.
--44 Mostrar proyectos con tareas que aún no han comenzado (fecha de inicio futura), indicando cuántas tareas están pendientes.
--45 Obtener la fecha más temprana y más tardía de contratación de empleados, y calcular el rango total de antigüedad en días.
--46 Listar tareas que se solapan en el tiempo para el mismo empleado, mostrando pares de tareas que se cruzan con sus fechas.
--47 Mostrar empleados que han trabajado en proyectos con presupuesto mayor a 1,000,000, junto con la suma de presupuestos de esos proyectos. 
--48 Listar tareas ordenadas por proyecto y fecha de inicio, y mostrar para cada tarea la posición ordinal dentro del proyecto (ejemplo: tarea 1 de 5).
--49 Mostrar proyectos donde ninguna tarea está ‘Completada’, indicando el porcentaje de tareas en cada estado.
--50 Obtener la duración promedio de las tareas por empleado, considerando solo tareas terminadas.
--51 Mostrar los empleados que no han sido asignados a ninguna tarea, junto con su ubicación y antigüedad.
--52 Listar empleados y el número de proyectos distintos en los que trabajan, mostrando también el promedio de tareas por proyecto.
--53 Mostrar las tareas que han durado más de 30 días, junto con el proyecto y el empleado asignado.
--54 Obtener el promedio, mínimo y máximo salario de los empleados, desglosado por ubicación.
--55 Listar empleados cuyo correo electrónico contiene un dominio específico (por ejemplo, ‘@empresa.com’), y mostrar el porcentaje que representan respecto al total.
--56 Mostrar los proyectos con la mayor diferencia entre fecha de inicio y fin, indicando duración en días y porcentaje respecto al proyecto más largo.
--57 Obtener los empleados que fueron contratados el mismo día que su proyecto comenzó, mostrando proyecto y fecha de contratación.
--58 Listar tareas y proyectos que comienzan y terminan en el mismo mes y año, mostrando duración y estado.
--59 Mostrar la cantidad de proyectos por año de inicio, junto con el presupuesto promedio y total por año.
--60 Listar empleados y sus tareas, mostrando el porcentaje de avance inferido del estado (por ejemplo, Pendiente=0%, En Progreso=50%, Completada=100%).
