------------------------------------------------------------------------------------------------------------------------------------
--Ejercicios SQL Básicos (1–20) 
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[1]-Crear la relación FK entre EMPLEADO y UBICACION
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE EMPLEADO
	--ADD CONSTRAINT Punto1_FkEmpleado_Ubicacion
	--FOREIGN KEY (FK_UbicacionId)
	--REFERENCES UBICACION(Id_Ubicacion)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[2]-Crear la relación FK entre TAREAS y EMPLEADO.
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE TAREAS
	--ADD CONSTRAINT Punto2_FkTareas_Empleados
	--FOREIGN KEY (FK_EmpleadoId)
	--REFERENCES EMPLEADO(Id_Empleado)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[3]-Crear la relación FK entre TAREAS y PROYECTO.
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE TAREAS
	--ADD CONSTRAINT Punto3_FkTareas_Proyectos
	--FOREIGN KEY (FK_ProyectoId)
	--REFERENCES PROYECTO(Id_Proyecto)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[4]-Insertar 20 registros en la tabla UBICACION, con diferentes nombres y ubicaciones (por ejemplo, ciudades o sucursales).
------------------------------------------------------------------------------------------------------------------------------------
--Bogota
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Chapinero','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Usaquen','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Teusaquillo','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora La Candelaria', 'Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Suba','Bogota')
------------------------------------------------------------------------------------------------------------------------------------
--Medellin
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Poblado','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Laureles','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Envigado','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Belen','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Castilla','Medellin')
------------------------------------------------------------------------------------------------------------------------------------
--Cali
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora San Antonio','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Granada','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Nacional','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Pampalinda','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Ciudad Jardin','Cali')
------------------------------------------------------------------------------------------------------------------------------------
--Barranquilla
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Alto Prado','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Villa Santos','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Ciudad Jardin','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora El Prado','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Riomar','Barranquilla')
------------------------------------------------------------------------------------------------------------------------------------
--DUAL
------------------------------------------------------------------------------------------------------------------------------------
----DBCC CHECKIDENT ('Ubicacion', RESEED, 20)
--INSERT INTO UBICACION (Nombre, Ubicacion) VALUES ('DISTRIBUIDORA DUAL BM','Bogota Medellin')
--INSERT INTO UBICACION (Nombre, Ubicacion) VALUES ('DISTRIBUIDORA DUAL BC','Bogota Cali')
--INSERT INTO UBICACION (Nombre, Ubicacion) VALUES ('DISTRIBUIDORA DUAL BB','Bogota Barranquilla')
--INSERT INTO UBICACION (Nombre, Ubicacion) VALUES ('DISTRIBUIDORA DUAL MC','Medellin Cali')
------------------------------------------------------------------------------------------------------------------------------------
--[5]-Insertar 20 registros en la tabla EMPLEADO, incluyendo nombre, apellido, email, salario (varios rangos), fecha de contratación y un FK válido a la tabla UBICACION.
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Bogota 1
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,Fk_UbicacionId) VALUES ('Jhon Fredy','Rincon Pelayo','jrinconp@distribuidora.com',12000000,'2025-01-01',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Juan','Perez','jperez@distribuidora.com',8000000,'2025-01-02',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Maria','Rodriguez','mrodriguez@distribuidora.com',850000,'2025-01-03',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Carlos','Gomez','cgomez@distribuidora.com',4000000,'2025-01-04',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Ana','Martinez','amartinez@distribuidora.com',7000000,'2025-01-05',1)
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Medellin 2
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Luis','Hernandez','lhernandez@distribuidora.com',1000000,'1995-01-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Laura','Sanchez','lsanchez@distribuidora.com',2000000,'1995-02-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('David','Ramirez','dramirez@distribuidora.com',3000000,'1995-03-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Sofia','Torres','storres@distribuidora.com',4000000,'1995-04-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Andres','Diaz','adiaz@distribuidora.com',5000000,'1995-05-01',2)
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Cali 3
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Camila','Florez','cflorez@distribuidora.com',1000000,'2000-01-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Alejandro','Morales','amorales@distribuidora.com',2000000,'2000-02-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Valentina','Castro','vcastro@distribuidora.com',3000000,'2000-03-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Jorge','Vargas','jvargas@distribuidora.com',4000000,'2000-04-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Daniela','Rojas','drojas@distribuidora.com',5000000,'2000-05-01',3)
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Barranquilla 4
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Felipe','Jimenez','fjimenez@distribuidora.com',1100000,'2010-01-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Isabella','Medina','imedina@distribuidora.com',2200000,'2010-02-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Ricardo','Silva','rsilva@distribuidora.com',3300000,'2010-03-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Gabriela','Ortiz','gortiz@distribuidora.com',4400000,'2010-04-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Nicolas','Cruz','ncruz@distribuidora.com',5500000,'2010-05-01',4)
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Dual
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Camila','Morales','cmorales_dualBogotaMedellin@distribuidora.com',5000000,'2020-01-01',21)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Juan','Ruiz','jruiz_dualBogotaMedellin@distribuidora.com',5000000,'2020-01-01',21)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Alberto','Arenas','aarenas_dualBogotaCali@distribuidora.com',5000000,'2020-01-01',22)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Andres','Andrade','aandrade_dualBogotaCali@distribuidora.com',5000000,'2020-01-01',22)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Alicia','Arce','aarce_dualBogotaBarranquilla@distribuidora.com',5000000,'2020-01-01',23)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Adriana','Acevedo','aacevedo_dualBogotaBarranquilla@distribuidora.com',5000000,'2020-01-01',23)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Antonio','Ayala','aayala_dualMedellinCali@distribuidora.com',5000000,'2020-01-01',24)
--INSERT INTO EMPLEADO (Nombre, Apellido, Email, Salario, Fecha_Contratacion, FK_UbicacionId) VALUES ('Axel','Andrade','aandrade_dualMedellinCali@distribuidora.com',5000000,'2020-01-01',24)
------------------------------------------------------------------------------------------------------------------------------------
--[6]-Insertar 20 registros en la tabla PROYECTO, con diferentes nombres, fechas de inicio y fin (fechas válidas y coherentes), y presupuestos variados.
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos Bogota
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Chapinero Bogota','2020-01-01','2030-01-01',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Usaquen Bogota','2025-01-01','2030-01-01',60000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Teusaquillo Bogota','2024-01-01','2030-01-01',50000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil La Candelaria Bogota','2023-01-01','2030-01-01',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Suba Bogota','2022-01-01','2030-01-01',30000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos Medellin
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Poblado Medellin','2010-01-01','2050-01-01',50000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Laureles Medellin','2009-01-01','2050-01-01',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Envigado Medellin','2008-01-01','2050-01-01',30000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Belen Medellin','2007-01-01','2050-01-01',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Castilla Medellin','2006-01-01','2050-01-01',10000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos Cali
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil SanAntonio Cali','2025-01-01','2025-12-01',1000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Granada Cali','2025-01-01','2025-12-02',2000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Nacional Cali','2025-01-01','2025-12-03',3000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Pampalinda Cali','2025-01-01','2025-12-04',4000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Ciudad Jardin Cali','2025-01-01','2025-12-05',5000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos Barranquilla
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Alto prado Barranquilla','2018-01-5','2025-12-01',50000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Villa Santos Barranquilla','2018-02-10','2025-12-02',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Ciudad Jardin Barranquilla','2018-03-15','2025-12-03',30000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil El Prado Barranquilla','2018-04-20','2025-12-04',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Itil Riomar Barranquilla','2018-05-25','2025-12-05',10000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos [Bogota_Medellin]
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Proyecto Andino','2025-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio,Fecha_Fin,Presupuesto) VALUES ('Dual Ruta Del Cafe','2025-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Nexo Capital Antioquia','2025-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Puente De La Montana','2025-01-01','2025-12-31',30000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Alianza Del Eje Andino','2025-01-01','2025-12-31',30000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos [Bogota_Cali]
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Proyecto Altiplano Pacifico','2025-01-01','2025-12-31',10000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Ruta De La Sabana','2025-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Eje Cultural Del Occidente','2025-01-01','2025-12-31',30000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Conexion Cordillera Central','2025-01-01','2025-12-31',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Red Valle Cundinamarca','2025-01-01','2025-12-31',50000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos [Bogota_Barranquilla]
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Proyecto Sabana Caribe','2025-01-01','2025-12-31',10000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Ruta Del Magdalena','2025-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Puente Andino Caribe','2025-01-01','2025-12-31',30000000) 
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Alianza Interior Costa','2025-01-01','2025-12-31',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Red Bogota Atlantico','2025-01-01','2025-12-31',50000000)
------------------------------------------------------------------------------------------------------------------------------------
--Proyectos [Medellin_Cali]
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Eje Del Valle Interandino','2025-01-01','2025-12-31',10000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Ruta Del Progreso Andino','2024-01-01','2025-12-31',20000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Conexion Cafetera Pacifico','2023-01-01','2025-12-31',30000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Proyecto Suroccidente Unido','2022-01-01','2025-12-31',40000000)
--INSERT INTO PROYECTO (Nombre, Fecha_Inicio, Fecha_Fin, Presupuesto) VALUES ('Dual Red Medellin Cali','2021-01-01','2025-12-31',50000000)
------------------------------------------------------------------------------------------------------------------------------------
--[7]-Insertar 20 registros en la tabla TAREAS, cada una con descripción, estado (por ejemplo: 'Pendiente', 'En Progreso', 'Completada'), fechas de inicio y fin, y claves foráneas que referencien empleados y proyectos existentes.
------------------------------------------------------------------------------------------------------------------------------------
--Tareas Bogota
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Chapinero','Pendiente',1,1,'2020-01-01','2030-01-01','Bogota')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Usaquen','Pendiente',2,2,'2025-01-01','2030-01-01','Bogota')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Teusaquillo','En Progreso',3,3,'2024-01-01','2030-01-01','Bogota')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil La Candelaria','En Progreso',4,4,'2023-01-01','2030-01-01','Bogota')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Suba','En Progreso',5,5,'2022-01-01','2030-01-01','Bogota')
------------------------------------------------------------------------------------------------------------------------------------
--Tareas Medellin
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Poblado','Pendiente',6,6,'2010-01-01','2050-01-01','Medellin')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Laureles','Pendiente',7,7,'2009-01-01','2050-01-01','Medellin')
--INSERT INTO TAREAS (Descripcion,Estado,Fk_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Envigado','En Progreso',8,8,'2008-01-01','2050-01-01','Medellin')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Belen','En Progreso',9,9,'2007-01-01','2050-01-01','Medellin')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Castilla','En Progreso',10,10,'2006-01-01','2050-01-01','Medellin')
------------------------------------------------------------------------------------------------------------------------------------
--Tareas Cali
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil SanAntonio','Pendiente',11,11,'2025-01-01','2025-12-01','Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Granada','Pendiente',12,12,'2025-01-01','2025-12-02','Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Nacional','En Progreso',13,13,'2025-01-01','2025-12-03','Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Pampalinda','En Progreso',14,14,'2025-01-01','2025-12-01','Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Ciudad Jardin','En Progreso',15,15,'2025-01-01','2025-12-05','Cali')
------------------------------------------------------------------------------------------------------------------------------------
--Tareas Barranquilla
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Alto prado','Terminada',16,16,'2018-01-05','2025-12-01','Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Villa Santos','Terminada',17,17,'2018-02-10','2025-12-02','Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Ciudad Jardin','Terminada',18,18,'2018-03-15','2025-12-03','Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil El Prado','Terminada',19,19,'2018-04-20','2025-12-04','Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_EmpleadoId,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Itil Riomar','Terminada',20,20,'2018-05-25','2025-12-05','Barranquilla')
------------------------------------------------------------------------------------------------------------------------------------
--Tareas EMPLEADO_TAREA
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,1)
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,2)
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,3)
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,4)
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,5)
--INSERT INTO EMPLEADO_TAREA (Fk_EmpleadoId, FK_TareaId) VALUES (1,6)
------------------------------------------------------------------------------------------------------------------------------------
--Tareas Duo
------------------------------------------------------------------------------------------------------------------------------------
--INSERT INTO TAREAS (Descripcion, Estado, FK_ProyectoId, Fecha_Inicio, Fecha_Fin, Ciudad_Proyecto) VALUES ('Dual Proyecto Andino','Pendiente',21,'2025-01-01','2025-12-31','Bogota Medellin')
--INSERT INTO TAREAS (Descripcion, Estado, FK_ProyectoId, Fecha_Inicio, Fecha_Fin, Ciudad_Proyecto) VALUES ('Dual Ruta Del Cafe','Pendiente',22,'2025-12-31','2025-12-31','Bogota_Medellin') 
--INSERT INTO TAREAS (Descripcion, Estado, FK_ProyectoId, Fecha_Inicio, Fecha_Fin, Ciudad_Proyecto) VALUES ('Dual Nexo Capital Antioquia','Pendiente',23,'2025-01-01','2025-12-31','Bogota_Medellin')
--INSERT INTO TAREAS (Descripcion, Estado, FK_ProyectoId, Fecha_Inicio, Fecha_Fin, Ciudad_Proyecto) VALUES ('Dual Puente De La Montana','Pendiente',24,'2025-01-01','2025-12-31','Bogota_Medellin')
--INSERT INTO TAREAS (Descripcion, Estado, FK_ProyectoId, Fecha_Inicio, Fecha_Fin, Ciudad_Proyecto) VALUES ('Dual Alianza Del Eje Andino','Pendiente',25,'2025-01-01','2025-12-31','Bogota_Medellin')

--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Proyecto Altiplano Pacifico','Pendiente',26,'2025-01-01','2025-12-31','Bogota_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,Fk_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Ruta De La Sabana','Pendiente',27,'2025-01-01','2025-12-31','Bogota_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Eje Cultural Del Occidente','Pendiente',28,'2025-01-01','2025-12-31','Bogota_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Conexion Cordillera Central','Pendiente',29,'2025-01-01','2025-12-31','Bogota_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Red Valle Cundinamarca','Pendiente',30,'2025-01-01','2025-12-31','Bogota_Cali')

--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Proyecto Sabana Caribe','Pendiente',31,'2025-01-01','2025-12-31','Bogota_Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Ruta Del Magdalena','Pendiente',32,'2025-01-01','2025-12-31','Bogota_Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Puente Andino Caribe','Pendiente',33,'2025-01-01','2025-12-31','Bogota_Barranquilla')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Alianza Interior Costa','Pendiente',34,'2025-01-01','2025-12-31','Bogota_Barranquilla')
----INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Red Bogota Atlantico','Pendiente',35,'2025-01-01','2025-12-31','Bogota_Barranquilla')

--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Eje Del Valle Interandino','Pendiente',36,'2025-01-01','2025-12-31','Medellin_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Ruta Del Progreso Andino','Pendiente',37,'2025-01-01','2025-12-31','Medellin_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Conexion Cafetera Pacifico','Pendiente',38,'2025-01-01','2025-12-31','Medellin_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Proyecto Suroccidente Unido','Pendiente',39,'2025-01-01','2025-12-31','Medellin_Cali')
--INSERT INTO TAREAS (Descripcion,Estado,FK_ProyectoId,Fecha_Inicio,Fecha_Fin,Ciudad_Proyecto) VALUES ('Dual Red Medellin Cali','Pendiente',40,'2025-01-01','2025-12-31','Medellin_Cali')
------------------------------------------------------------------------------------------------------------------------------------
--Consultas básicas
------------------------------------------------------------------------------------------------------------------------------------
--[8]-Mostrar todos los empleados.
	--SELECT a.Id_Empleado, a.Nombre, a.Apellido, a.Email, a.Salario, a.Fecha_Contratacion, a.FK_UbicacionId AS Ubicacion 
	--FROM EMPLEADO a
------------------------------------------------------------------------------------------------------------------------------------
--[9]-Listar nombres y apellidos de empleados con salario mayor a 3000.   
	--SELECT a.Nombre, a.Apellido, a.Salario FROM EMPLEADO a
	--WHERE Salario > 3000
------------------------------------------------------------------------------------------------------------------------------------
--[10]-Mostrar todos los registros de la tabla UBICACION.
	--SELECT a.Id_Ubicacion, a.Nombre, a.Ubicacion FROM UBICACION a
------------------------------------------------------------------------------------------------------------------------------------
--[11]-Mostrar proyectos con sus presupuestos ordenados de mayor a menor.
	--SELECT a.Id_Proyecto, a.Nombre, a.Fecha_Inicio, a.Fecha_Fin, a.Presupuesto FROM PROYECTO a
	--ORDER BY Presupuesto DESC
------------------------------------------------------------------------------------------------------------------------------------
--[12]-Mostrar todas las tareas que estén en estado “Pendiente”.
	--SELECT * FROM TAREAS a
	--WHERE a.Estado = 'Pendiente'
------------------------------------------------------------------------------------------------------------------------------------
--[13]-Listar tareas asignadas al empleado con Id_Empleado = 1.
	--SELECT * FROM TAREAS a
	--WHERE a.FK_EmpleadoId = 1
------------------------------------------------------------------------------------------------------------------------------------
--[14]-Mostrar empleados ordenados por salario de forma descendente.
	--SELECT a.Id_Empleado, a.Nombre, a.Apellido, a.Email, a.Salario, a.Fecha_Contratacion, a.FK_UbicacionId FROM EMPLEADO a
	--ORDER BY Salario DESC
------------------------------------------------------------------------------------------------------------------------------------
--[15]-Obtener la cantidad total de tareas registradas.
	--SELECT COUNT(*) AS TotalTareasRegistradas FROM TAREAS a
------------------------------------------------------------------------------------------------------------------------------------
--[16]-Mostrar nombre completo (nombre + apellido) y fecha de contratación de todos los empleados.
	--SELECT a.Nombre, a.Apellido, a.Fecha_Contratacion FROM EMPLEADO a
------------------------------------------------------------------------------------------------------------------------------------
--[17]-Listar proyectos que iniciaron después del 1 de enero de 2023.
	--SELECT * FROM PROYECTO
	--WHERE Fecha_Inicio > '2023-01-01'
------------------------------------------------------------------------------------------------------------------------------------
--[18]-Mostrar empleados cuyo salario esté entre 2000 y 4000.
	--SELECT * FROM EMPLEADO
	--WHERE Salario BETWEEN 2000000 AND 4000000
------------------------------------------------------------------------------------------------------------------------------------
--[19]-Mostrar tareas que comienzan en una fecha específica dada.
	--SELECT * FROM TAREAS
	--WHERE Fecha_Inicio = '2020-01-01'
------------------------------------------------------------------------------------------------------------------------------------
--[20]-Mostrar los empleados junto con el nombre de su ubicación (JOIN entre EMPLEADO y UBICACION).
	--SELECT a.Nombre, a.Apellido, b.Nombre, b.Ubicacion FROM EMPLEADO a
	--INNER JOIN UBICACION b ON a.FK_UbicacionId = b.Id_Ubicacion
------------------------------------------------------------------------------------------------------------------------------------