---------------------------------
--Ejercicios SQL Básicos (1–20) 
---------------------------------

------------------------------------------------------------------------------------------------------------------------------------
--[1]-Crear la relación FK entre EMPLEADO y UBICACION
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE EMPLEADO
	--ADD CONSTRAINT Punto1_FkEmpleado_Ubicacion
	--FOREIGN KEY (FK_UbicacionId)
	--REFERENCES UBICACION(Id_Ubicacion)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[2]-Crear la relación FK entre TAREAS y EMPLEADO.
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE TAREAS
	--ADD CONSTRAINT Punto2_FkTareas_Empleados
	--FOREIGN KEY (FK_EmpleadoId)
	--REFERENCES EMPLEADO(Id_Empleado)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[3]-Crear la relación FK entre TAREAS y PROYECTO.
------------------------------------------------------------------------------------------------------------------------------------
	--[ALTER TABLE TAREAS
	--ADD CONSTRAINT Punto3_FkTareas_Proyectos
	--FOREIGN KEY (FK_ProyectoId)
	--REFERENCES PROYECTO(Id_Proyecto)
	--]
------------------------------------------------------------------------------------------------------------------------------------
--[4]-Insertar 20 registros en la tabla UBICACION, con diferentes nombres y ubicaciones (por ejemplo, ciudades o sucursales).
------------------------------------------------------------------------------------------------------------------------------------
--Bogota
---------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Chapinero','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Usaquen','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Teusaquillo','Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora La Candelaria', 'Bogota')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Suba','Bogota')
---------------------------------
--Medellin
---------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Poblado','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Laureles','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Envigado','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Belen','Medellin')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Castilla','Medellin')
---------------------------------
--Cali
---------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora San Antonio','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Granada','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Nacional','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Pampalinda','Cali')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Ciudad Jardin','Cali')
---------------------------------
--Barranquilla
---------------------------------
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Alto Prado','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Villa Santos','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Ciudad Jardin','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora El Prado','Barranquilla')
--INSERT INTO Ubicacion (Nombre, Ubicacion) VALUES ('Distribuidora Riomar','Barranquilla')
------------------------------------------------------------------------------------------------------------------------------------
--[5]-Insertar 20 registros en la tabla EMPLEADO, incluyendo nombre, apellido, email, salario (varios rangos), fecha de contratación y un FK válido a la tabla UBICACION.
------------------------------------------------------------------------------------------------------------------------------------
--Contrataciones Bogota 1
---------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,Fk_UbicacionId) VALUES ('Jhon Fredy','Rincon Pelayo','jrinconp@distribuidora.com',12000000,'2025-01-01',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Juan','Perez','jperez@distribuidora.com',8000000,'2025-01-02',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Maria','Rodriguez','mrodriguez@distribuidora.com',850000,'2025-01-03',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Carlos','Gomez','cgomez@distribuidora.com',4000000,'2025-01-04',1)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Ana','Martinez','amartinez@distribuidora.com',7000000,'2025-01-05',1)
---------------------------------
--Contrataciones Medellin 2
---------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Luis','Hernandez','lhernandez@distribuidora.com',1000000,'1995-01-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Laura','Sanchez','lsanchez@distribuidora.com',2000000,'1995-02-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('David','Ramirez','dramirez@distribuidora.com',3000000,'1995-03-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Sofia','Torres','storres@distribuidora.com',4000000,'1995-04-01',2)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Andres','Diaz','adiaz@distribuidora.com',5000000,'1995-05-01',2)
---------------------------------
--Contrataciones Cali 3
---------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Camila','Florez','cflorez@distribuidora.com',1000000,'2000-01-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Alejandro','Morales','amorales@distribuidora.com',2000000,'2000-02-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Valentina','Castro','vcastro@distribuidora.com',3000000,'2000-03-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Jorge','Vargas','jvargas@distribuidora.com',4000000,'2000-04-01',3)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Daniela','Rojas','drojas@distribuidora.com',5000000,'2000-05-01',3)
---------------------------------
--Contrataciones Barranquilla 4
---------------------------------
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Felipe','Jimenez','fjimenez@distribuidora.com',1100000,'2010-01-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Isabella','Medina','imedina@distribuidora.com',2200000,'2010-02-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Ricardo','Silva','rsilva@distribuidora.com',3300000,'2010-03-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Gabriela','Ortiz','gortiz@distribuidora.com',4400000,'2010-04-01',4)
--INSERT INTO Empleado (Nombre,Apellido,Email,Salario,Fecha_Contratacion,FK_UbicacionId) VALUES ('Nicolas','Cruz','ncruz@distribuidora.com',5500000,'2010-05-01',4)







--6-Insertar 20 registros en la tabla PROYECTO, con diferentes nombres, fechas de inicio y fin (fechas válidas y coherentes), y presupuestos variados.
--7-Insertar 20 registros en la tabla TAREAS, cada una con descripción, estado (por ejemplo: 'Pendiente', 'En Progreso', 'Completada'), fechas de inicio y fin, y claves foráneas que referencien empleados y proyectos existentes.

---------------------------------
--Consultas básicas
---------------------------------
--8-Mostrar todos los empleados.
--9-Listar nombres y apellidos de empleados con salario mayor a 3000.
--10-Mostrar todos los registros de la tabla UBICACION.
--11-Mostrar proyectos con sus presupuestos ordenados de mayor a menor.
--12-Mostrar todas las tareas que estén en estado “Pendiente”.
--13-Listar tareas asignadas al empleado con Id_Empleado = 1.
--14-Mostrar empleados ordenados por salario de forma descendente.
--15-Obtener la cantidad total de tareas registradas.
--16-Mostrar nombre completo (nombre + apellido) y fecha de contratación de todos los empleados.
--17-Listar proyectos que iniciaron después del 1 de enero de 2023.
--18-Mostrar empleados cuyo salario esté entre 2000 y 4000.
--19-Mostrar tareas que comienzan en una fecha específica dada.
--20-Mostrar los empleados junto con el nombre de su ubicación (JOIN entre EMPLEADO y UBICACION).